---
- hosts: localhost
  gather_facts: True
  sudo: True
  tasks:
    - ec2_facts:
    - debug: msg= "{{ hostvars[inventory_hostname]['ansible_ec2_instance_id'] }}"

#- hosts: delete
#  gather_facts: True
#  connection: local
#  vars:
#    region: "us-east-1"
#  tasks:
#    - name: destroy all instances
#      ec2: state='absent'
#           region={{ region }}
#           instance_ids={{ item }}
#           wait=true
#      with_items: hostvars[inventory_hostname]['ansible_ec2_instance_id']