---
- name: Terminate {{ec2_id}} instance in {{aws_region}}
  local_action:
      module: ec2
      state: 'absent'
      region: '{{aws_region}}'
      instance_ids: '{{ec2_id}}'


#when: ec2_tags.tags.Name is defined