---
# Basic decommissioning example

- name: Delete devel EC2 instances
  hosts: security_group_*my-security-group*           # <-- MAGIC IS HERE!
  connection: local
  gather_facts: False

  tasks:
  - name: Terminate {{ec2_id}} instance in {{aws_region}}
    local_action:
        module: ec2
        state: 'absent'
        region: '{{aws_region}}'
        instance_ids: '{{ec2_id}}'

- name: Delete '*my-security-group*' security group
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Take '*my-security-group*' security group down
    local_action:
        module: ec2_group
        name: *my-security-group*
        description: "A Security group"
        region: "{{aws_region}}"
        state: 'absent'